# Dependencies
markdown: kramdown
#redcarpet:
#  extensions:     [strikethrough,smart,with_toc_data]
highlighter: rouge

# Permalinks
permalink: /posts/:title/

# User Configuration
title: "Alex Sikilinda"
tagline: "A programmer's journey"
description: "Shipping software, mostly with .NET"
url: https://sikilinda.com
baseurl: "/"
paginate: 5
excerpt_separator: "<br>"
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate

plugins: [jekyll-paginate]

# Author Info
author:
  name: "Alex Sikilinda"
  url: "https://sikilinda.com"

# Social Integration
social:
  twitter: AlexSikilinda
  disqus: sikilinda
  addthis_pubid: ra-56dcb98b76d5a726

# Google Analytics Configuration
# Proxy response must be in JSON and should have the fields - ga:pagePath, ga:pageview
google_analytics:
  tracking_id: your_google_analytics_tracking_id
  super_proxy_url: your_super_proxy_url

# Github
github:
  repo: AlexSikilinda
  feedback: your_github_repo_issues_page_url

# Version Info
version: 0.0.5
