# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:     [strikethrough,smart,with_toc_data]
highlighter:      rouge

# Permalinks
permalink:        /posts/:title/

# User Configuration
title:            'Alex Sikilinda'
tagline:          'A bootstrap for Jekyll'
description:      'Poor english zone.'
url:              http://sikilinda.com
baseurl:          '/'
paginate:         3
excerpt_separator: '<br>'
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-paginate

# Author Info
author:
  name:           'Alex Sikilinda'
  url:            'http://sikilinda.com'

# Social Integration
social:
  twitter:        your_twitter_handle
  disqus:         sikilinda
  addthis_pubid:  ra-56dcb98b76d5a726

# Google Analytics Configuration
# Proxy response must be in JSON and should have the fields - ga:pagePath, ga:pageview
google_analytics:
  tracking_id:      your_google_analytics_tracking_id
  super_proxy_url:  your_super_proxy_url

# Github
github:
  repo:           your_github_repo
  feedback:       your_github_repo_issues_page_url

# Version Info
version:          0.0.5